spring:
  datasource:
    url: jdbc:mysql://localhost:3306/MPLB
    username: dlrkdus
    password: aa1111
    driver-class: com.mysql.cj.jdbc.Driver
  jpa:
    #전송 쿼리 확인
    show-sql: true
    properties:
      hibernate:
        format_sql: true

    #테이블 생성 후에 data.sql 실행
    defer-datasource-initialization: true


